spring:
  application:
    name: qflowserver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-3-231-16-122.compute-1.amazonaws.com:5432/dcbsobfdckbi0d?user=ggzdpttkzqrqaj&password=0f9a3e551759e90c35dfe5e2c8b492dfac435f6d7122e00e3fa4ee451048eaea&sslmode=require
    username: ggzdpttkzqrqaj
    password: 0f9a3e551759e90c35dfe5e2c8b492dfac435f6d7122e00e3fa4ee451048eaea

server:
  port: 8445

# Debug query JPA
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

hibernate:
  types:
    print:
      banner: false


#    # Feign configuration
#feign:
#  client:
#    config:
#      default:
#        loggerLevel: FULL
#
#hystrix:
#  command:
#    HystrixCommandKey:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 5000
